# RBAC authn and authz
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{template "elasticsearch.name" . }}-logging
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{template "elasticsearch.name" .}}-logging-{{.Release.Namespace}}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4}}
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "endpoints"
    verbs:
      - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{template "elasticsearch.name" . }}-logging-{{.Release.Namespace}}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
    k8s-app: elasticsearch-logging
subjects:
- kind: ServiceAccount
  name: {{template "elasticsearch.name" . }}-logging
  namespace: {{.Release.Namespace}}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{template "elasticsearch.name" . }}-logging-{{.Release.Namespace}}
  apiGroup: ""
