apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.name" . }}-discovery
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
  ports:
    - name: transport
      port: 9300
      protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.name" . | nindent 4 }}-logging
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elasticsearch.labels"  . | nindent 4 }}
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: db
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
