apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: thanos-query
spec:
  ports:
    - name: grpc
      port: {{ .Values.thanosQuery.grpcPort }}
      targetPort: grpc
    - name: http
      port: {{ .Values.thanosQuery.httpPort }}
      targetPort: http
  selector:
    app.kubernetes.io/name: thanos-query
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: thanos-query
spec:
  replicas: {{ .Values.thanosQuery.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-query
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-query
    spec:
      containers:
        - args:
            - query
            - --log.level=debug
            - --query.auto-downsampling
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:9090
            - --query.partial-response
            - --query.replica-label=prometheus_replica
            - --query.replica-label=rule_replica
            - --store=dnssrv+_grpc._tcp.prometheus-headless.thanos.svc.cluster.local
            - --store=dnssrv+_grpc._tcp.thanos-rule.thanos.svc.cluster.local
            - --store=dnssrv+_grpc._tcp.thanos-store.thanos.svc.cluster.local
          image: quay.io/thanos/thanos:{{ .Values.image.thanosTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            failureThreshold: 4
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            periodSeconds: 30
          name: thanos-query
          ports:
            - containerPort: 10901
              name: grpc
            - containerPort: 9090
              name: http
          readinessProbe:
            failureThreshold: 20
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            periodSeconds: 5
          terminationMessagePolicy: FallbackToLogsOnError
          {{- with .Values.thanosQuery.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      terminationGracePeriodSeconds: 120
      {{- with .Values.thanosQuery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.thanosQuery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.thanosQuery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
