---
# 采集数据库相关的日志
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{include "fluentbit.name" . }}-database
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "fluentbit.labels" . | nindent 4 }}
    type: database
spec:
  selector:
    matchLabels:
      {{- include "fluentbit.selectorLabels" . | nindent 6 }}
      type: database
  template:
    metadata:
      labels:
        {{- include "fluentbit.labels" . | nindent 8 }}
        type: database
    spec:
      {{- with .Values.database.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{end}}
      containers:
        - name: fluent-bit
          image: {{include "fluentbit.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 2020
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit-db.conf"]
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.esHost | quote }}
            - name: FLUENT_ELASTICSEARCH_PORT
              value: {{ .Values.esPort | quote }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibpodcontainers
              mountPath: /var/lib/kubelet/pods
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: containers
              mountPath: {{ .Values.containerDir }}
              readOnly: true
            - name: limit
              mountPath: /etc/security/limits.conf
              subPath: limits
            - mountPath: /etc/localtime
              name: localtime
      terminationGracePeriodSeconds: 10
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibpodcontainers
          hostPath:
            path: {{ .Values.kubeletPodsDir }}
        - name: containers
          hostPath:
              path: {{ .Values.containerDir }}
        - name: fluent-bit-config
          configMap:
            name: {{include "fluentbit.name" . }}
        - name: limit
          configMap:
            name: {{include "fluentbit.name" . }}
            items:
              - key: limits.conf
                path: limits
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
          name: localtime
      serviceAccountName: fluent-bit
---
# 采集k8s容器相关的日志
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{include "fluentbit.name" . }}-k8s
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "fluentbit.labels" . | nindent 4 }}
    type: k8s
spec:
  selector:
    matchLabels:
      {{- include "fluentbit.selectorLabels" . | nindent 6 }}
      type: k8s
  template:
    metadata:
      labels:
        {{- include "fluentbit.labels" . | nindent 8 }}
        type: k8s
    spec:
      {{- with .Values.k8s.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{end}}
      containers:
        - name: fluent-bit
          image: {{include "fluentbit.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 2020
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit-k8s.conf"]
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.esHost | quote }}
            - name: FLUENT_ELASTICSEARCH_PORT
              value: {{ .Values.esPort | quote }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: {{ .Values.containerDir }}
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: limit
              mountPath: /etc/security/limits.conf
              subPath: limits
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: {{ .Values.containerDir }}
        - name: fluent-bit-config
          configMap:
            name: {{include "fluentbit.name" . }}
        - name: limit
          configMap:
            name: {{include "fluentbit.name" . }}
            items:
              - key: limits.conf
                path: limits
        - hostPath:
            path: /etc/localtime
          name: localtime
      serviceAccountName: fluent-bit
